### Learning saving Tensor Data 

April 31, 2022 

_This was surprisingly hard_

https://www.tensorflow.org/api_docs/python/tf/data/experimental/save

In [1]:
# # Unsuccessful attempt via tf.data.experimental.save

# import tempfile

# path = os.path.join(tempfile.gettempdir(), "saved_data")
# # Save a dataset
# #dataset = tf.data.Dataset.range(2)
# dataset = GAN
# tf.data.experimental.save(dataset, path)
# #new_dataset = tf.data.experimental.load(path)
# # for elem in new_dataset:
# #   print(elem)

https://www.tensorflow.org/api_docs/python/tf/io/write_file

In [2]:
## This attempt was also unsuccessful 
#tf.io.write_file("GAN", GAN)

https://pytorch.org/docs/stable/generated/torch.save.html

In [3]:
# This attempt was also unsuccessful 
# import torch 
# torch.save(GAN, 'GAN.pt')

https://discuss.pytorch.org/t/what-is-the-recommended-format-to-save-data-in-pytorch/89047

In [4]:
# Saving tensor to file 

## I believe this has to be run in a kernel that supports Torch such as AMPTorch 0.1

## The OG code saves the files in my home folder -> data -> tmp
# import torch

# from pathlib import Path

# path = Path('~/data/tmp/').expanduser()

# tensor_a = torch.rand(2,3)
# tensor_b = torch.rand(1,3)

# db = {'a': tensor_a, 'b': tensor_b}

# torch.save(db, path/'torch_db')
# loaded = torch.load(path/'torch_db')
# print( loaded['a'] == tensor_a )
# print( loaded['b'] == tensor_b )

In [5]:
## This modified block of code saves the files in the project folder
import torch

from pathlib import Path

path = Path('/project/ds6050-soa2wg/team_lambda_II/').expanduser()

tensor_a = torch.rand(2,3)
tensor_b = torch.rand(1,3)

In [6]:
tensor_a

tensor([[0.9556, 0.7839, 0.4242],
        [0.5685, 0.5464, 0.9769]])

In [7]:
tensor_b

tensor([[0.5635, 0.5395, 0.4874]])

In [8]:
db = {'a': tensor_a, 'b': tensor_b}

torch.save(db, path/'torch_db')
loaded = torch.load(path/'torch_db')
print( loaded['a'] == tensor_a )
print( loaded['b'] == tensor_b )

tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True]])


In [20]:
loaded['a']

tensor([[0.9556, 0.7839, 0.4242],
        [0.5685, 0.5464, 0.9769]])

In [21]:
loaded['b']

tensor([[0.5635, 0.5395, 0.4874]])

In [11]:
# saving data in numpy

## The OG code saves the files in my home folder -> data -> tmp

# import numpy as np
# import pickle
# from pathlib import Path

# path = Path('~/data/tmp/').expanduser()
# path.mkdir(parents=True, exist_ok=True)

# lb,ub = -1,1
# num_samples = 5
# x = np.random.uniform(low=lb,high=ub,size=(1,num_samples))
# y = x**2 + x + 2

# # using save (to npy), savez (to npz)
# np.save(path/'x', x)
# np.save(path/'y', y)
# np.savez(path/'db', x=x, y=y)
# with open(path/'db.pkl', 'wb') as db_file:
#     pickle.dump(obj={'x':x, 'y':y}, file=db_file)

# ## using loading npy, npz files
# x_loaded = np.load(path/'x.npy')
# y_load = np.load(path/'y.npy')
# db = np.load(path/'db.npz')
# with open(path/'db.pkl', 'rb') as db_file:
#     db_pkl = pickle.load(db_file)

# print(x is x_loaded)
# print(x == x_loaded)
# print(x == db['x'])
# print(x == db_pkl['x'])
# print('done')

In [12]:
#saving data in numpy

# This modified block of code saves the files in the project folder

import numpy as np
import pickle
from pathlib import Path

path = Path('/project/ds6050-soa2wg/team_lambda_II/').expanduser()
path.mkdir(parents=True, exist_ok=True)

lb,ub = -1,1
num_samples = 5
x = np.random.uniform(low=lb,high=ub,size=(1,num_samples))
y = x**2 + x + 2

In [13]:
x

array([[-0.34956968, -0.33040486,  0.85253508,  0.12223225,  0.77482414]])

In [14]:
y

array([[1.77262928, 1.77876251, 3.57935115, 2.13717298, 3.37517658]])

In [15]:
# using save (to npy), savez (to npz)
np.save(path/'x', x)
np.save(path/'y', y)
np.savez(path/'db', x=x, y=y)
with open(path/'db.pkl', 'wb') as db_file:
    pickle.dump(obj={'x':x, 'y':y}, file=db_file)

## using loading npy, npz files
x_loaded = np.load(path/'x.npy')
y_load = np.load(path/'y.npy')
db = np.load(path/'db.npz')
with open(path/'db.pkl', 'rb') as db_file:
    db_pkl = pickle.load(db_file)

print(x is x_loaded)
print(x == x_loaded)
print(x == db['x'])
print(x == db_pkl['x'])
print('done')

False
[[ True  True  True  True  True]]
[[ True  True  True  True  True]]
[[ True  True  True  True  True]]
done


In [18]:
x_loaded

array([[-0.34956968, -0.33040486,  0.85253508,  0.12223225,  0.77482414]])

In [19]:
y_load

array([[1.77262928, 1.77876251, 3.57935115, 2.13717298, 3.37517658]])