__Learning np.squeeze()__

https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html

numpy.squeeze(a, axis=None)[source]
Remove axes of length one from a.

In [25]:
import numpy as np

In [26]:
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [27]:
x.shape

(1, 3, 1)

In [28]:
np.squeeze(x)

array([0, 1, 2])

In [29]:
np.squeeze(x).shape

(3,)

In [30]:
np.squeeze(x, axis = 2)

array([[0, 1, 2]])

In [31]:
np.squeeze(x, axis = 2).shape

(1, 3)